### ISSUE TITLE
Solve Pythong Error 

### ISSUE THREAD

**Issue by Rahulsharma0810** [ttys3/my-kitty-config#1]
```
❯ kitty --debug-input
[284 01:18:55.162272] Traceback (most recent call last):
  File "lib/python3.9/kitty/main.py", line 559, in main
  File "lib/python3.9/kitty/main.py", line 551, in _main
  File "lib/python3.9/kitty/main.py", line 293, in __call__
  File "lib/python3.9/kitty/main.py", line 271, in _run_app
  File "lib/python3.9/kitty/boss.py", line 364, in __init__
  File "lib/python3.9/kitty/boss.py", line 177, in listen_on
FileNotFoundError: [Errno 2] No such file or directory
```

Could you please tell me how to fix the above error?

**Comment by ttys3** [comment]
maybe it is caused by `listen_on unix:$XDG_RUNTIME_DIR/kitty.sock`

I think I'd better disable this

**Comment by ttys3** [comment]
this https://github.com/ttys3/my-kitty-config/commit/35a626263c9f3e08d456d5d63136c796964062e5 should fix your issue

**Comment by Rahulsharma0810** [comment]
Great Thanks
